---
apiVersion: v1
kind: Service
metadata:
  name: larvis
  labels:
    app: larvis
spec:
  clusterIP: None
  ports:
    - port: 8080
      name: larvis
  selector:
    app: larvis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: larvis
  labels:
    app: larvis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: larvis
  template:
    metadata:
      labels:
        app: larvis
    spec:
      containers:
        - name: larvis
          image: larvis
          ports:
            - containerPort: 8080
